apiVersion: apps/v1
kind: Deployment
metadata:
  name: front:v1end-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: website
        image:docker.io/kalyan/front:10
        ports:
        - containerPort: 80
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
                - key: nodename
                  operator: In
                  values:
                    - app-worker2
